modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "cool_commands"
version = "${version}"
displayName = "Cool Commands"
authors = "MrRandon"
description = '''
This is a mod to add cool commands, intended to be used with the cci mod.
'''
#logoFile = ""

[[dependencies.cool_commands]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cool_commands]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cool_commands]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "cool_commands.mixins.json"
